"""add_postgresql_core_models

Revision ID: f68be6710ca6
Revises: 8223989eed0c
Create Date: 2026-08-15 18:46:13.002484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68be6710ca6'
down_revision: Union[str, Sequence[str], None] = '8223989eed0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'degraded', 'healthy', 'unhealthy', name='infrastructurestatus', native_enum=False), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_service_name'), 'infrastructure', ['service_name'], unique=False)
    op.create_index(op.f('ix_infrastructure_service_type'), 'infrastructure', ['service_type'], unique=False)
    op.create_index(op.f('ix_infrastructure_status'), 'infrastructure', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'operator', name='userrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incidentseverity', native_enum=False), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('resolution_status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='resolutionstatus', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['infrastructure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_resolution_status'), 'incidents', ['resolution_status'], unique=False)
    op.create_index(op.f('ix_incidents_service_id'), 'incidents', ['service_id'], unique=False)
    op.create_index('ix_incidents_service_status', 'incidents', ['service_id', 'resolution_status'], unique=False)
    op.create_index('ix_incidents_service_timestamp', 'incidents', ['service_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index('ix_incidents_status_severity', 'incidents', ['resolution_status', 'severity'], unique=False)
    op.create_index(op.f('ix_incidents_timestamp'), 'incidents', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_timestamp'), table_name='incidents')
    op.drop_index('ix_incidents_status_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index('ix_incidents_service_timestamp', table_name='incidents')
    op.drop_index('ix_incidents_service_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_service_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resolution_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_infrastructure_status'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_service_type'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_service_name'), table_name='infrastructure')
    op.drop_table('infrastructure')
    # ### end Alembic commands ###
